version: '3.8'

services:
  quizz-creator:
    image: registry.gitlab.com/fougereregent/quizz-creator/quizz
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quizz_creator.entrypoints=websecure"
      - "traefik.http.services.quizz_creator.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.quizz_creator.tls=true"
      - "traefik.http.routers.quizz_creator.rule=Host(`creator-quizz.damien-venant.ovh`)"
      - "traefik.http.routers.quizz_creator.tls.certresolver=myresolver"
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: traefik_default
