version: '3.8'

services:
  app:
    container-name: mayoo-application
    image: registry.gitlab.com/fougereregent/api-mayoo/app
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.application.entrypoints=websecure"
      - "traefik.http.services.application.loadbalancer.server.port=19006"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.application.tls=true"
      - "traefik.http.routers.application.rule=Host(`app.damien-venant.ovh`)"
      - "traefik.http.routers.application.tls.certresolver=myresolver"
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: traefik_default
