name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/test.yml
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./quizz-service
      run: docker build . --file /Dockerfile --tag my-image-name:$(date +%s)
