name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/reusable-build-workflow.yml
    
  build-quiz-api:
    runs-on: ubuntu-latest
    needs: ["call-workflow-1-in-local-repo"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./quizz-service
          file: ./quizz-service/apps/quizz-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizz-mayoo:latest

  build-game-api:
    runs-on: ubuntu-latest
    needs: ["call-workflow-1-in-local-repo"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./quizz-service
          file: ./quizz-service/apps/game-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/game-mayoo:latest

  build-quiz-creator:
    runs-on: ubuntu-latest
    needs: ["call-workflow-1-in-local-repo"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./quizz-creator
          file: ./quizz-creator/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quizz-creator:latest
  
 
  build-app-mayoo:
    runs-on: ubuntu-latest
    needs: ["call-workflow-1-in-local-repo"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./app-mayoo
          file: ./app-mayoo/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-mayoo:latest
