# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Test API Quiz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.10.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0
    - name: Run Install API
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: quizz-service
    - name: Run Install APP
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: app-mayoo
    - name: Build API
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: ./quizz-service
    - name: Test API
      uses: borales/actions-yarn@v4
      with:
        cmd: test quizz-service
        dir: quizz-service
